In [29]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import math as math
#import seaborn as sns


%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
a = np.arange(1,21)
print (a)
vect = (2**a)/a
print(vect)








[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  2.00000000e+00   2.00000000e+00   2.66666667e+00   4.00000000e+00
   6.40000000e+00   1.06666667e+01   1.82857143e+01   3.20000000e+01
   5.68888889e+01   1.02400000e+02   1.86181818e+02   3.41333333e+02
   6.30153846e+02   1.17028571e+03   2.18453333e+03   4.09600000e+03
   7.71011765e+03   1.45635556e+04   2.75941053e+04   5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
a = np.arange(6)
print(a)
vect = ((0.1)**(3*a))*(0.2)**(4*a)
print(vect.sum(dtype=np.double))

[0 1 2 3 4 5]
1.0000016


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [49]:
a = np.zeros((8,8),dtype=int)
a[1:8:2,::2]=1
a[::2,1:8:2]=1

print(a)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [65]:
X = np.random.random((5, 2))
print(X)
X_p = np.zeros((5,2),dtype = float)
X_p[:,0] = X[:,1]**2 + X[:,0]**2
X_p[:,1] = np.arctan2(X[:,1],X[:,0])
print(X_p)



[[ 0.42345566  0.94484028]
 [ 0.32309956  0.34905684]
 [ 0.23898355  0.07996032]
 [ 0.02439704  0.65329666]
 [ 0.67338303  0.88128508]]
[[ 1.07203786  1.14945946]
 [ 0.226234    0.82399691]
 [ 0.06350679  0.32287668]
 [ 0.42739174  1.53346917]
 [ 1.2301081   0.91833707]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [95]:
X = np.random.random((10, 10))
#X = np.arange(0,100).reshape(10,10)
print (X)
max = np.argmax(X)
m = max//10
n = max - m*10
print(max, m,n, X.max())


[[ 0.02289339  0.28546947  0.07401     0.36996202  0.59151384  0.82693085
   0.65030906  0.41851981  0.6783141   0.06138617]
 [ 0.37036314  0.5202576   0.47012995  0.27698291  0.50289797  0.96373488
   0.49572957  0.52021736  0.28465901  0.72261539]
 [ 0.76405969  0.88611852  0.74620376  0.69313275  0.91541863  0.63793771
   0.94314768  0.68610524  0.70313909  0.85516962]
 [ 0.54373523  0.16326706  0.68162284  0.42592563  0.68360352  0.23864874
   0.07028745  0.72692323  0.71811666  0.80721877]
 [ 0.18175598  0.96635836  0.99307956  0.26277744  0.56875021  0.21055751
   0.30179594  0.45587464  0.41059814  0.63724234]
 [ 0.51044549  0.81973806  0.08683251  0.74613546  0.49566023  0.21476184
   0.32904654  0.22434497  0.39239037  0.53492583]
 [ 0.74890837  0.61346548  0.60338778  0.26586119  0.46384931  0.07705894
   0.31391033  0.51830444  0.39314879  0.56036216]
 [ 0.39514794  0.79236831  0.206374    0.02541548  0.42588947  0.77697705
   0.68343057  0.36260138  0.90358144  0.20166687]


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [3]:
x = np.random.random((10, 2))
y = np.random.random((1, 2))
print(x)
print (y)
y1 = np.zeros((10,2), dtype = np.double)
y1[:,0] = y[0,0]
y1[:,1] = y[0,1]
print(x[np.argmin(np.sqrt((x[:,0]-y1[:,0])**2 + (x[:,0]-y1[:,0])**2)),:])


[[ 0.97554104  0.26762868]
 [ 0.56522829  0.40623149]
 [ 0.16368291  0.60793838]
 [ 0.28159091  0.85329667]
 [ 0.72041898  0.77186386]
 [ 0.50402591  0.80048069]
 [ 0.48046336  0.26419683]
 [ 0.98641677  0.43537602]
 [ 0.09417172  0.81193615]
 [ 0.36200701  0.9735994 ]]
[[ 0.90696227  0.94732478]]
[ 0.97554104  0.26762868]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [19]:
 x = np.arange(-3,4)
y = [[ x[x<0]**2+2*x[x<0] + 6],[x[(x>=0)&(x<=2)] + 6],[x[x>=2]**2+4*x[x>=2]-4]]
print(y)

[[array([9, 6, 5])], [array([6, 7, 8])], [array([ 8, 17])]]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [3]:
X = np.random.random((10, 10))

mean = np.mean(X,axis = 1)
#print(X,mean)
print( np.array([X[i] - mean[i] for i in range(0,len(X))],dtype = np.double))


## your code

[[ 0.07935842 -0.12631142 -0.23689524  0.17185621  0.39025537  0.06053571
   0.12571895 -0.41335344  0.22977248 -0.28093704]
 [-0.23421483 -0.38716702 -0.33381969 -0.19205101 -0.14575943  0.23513105
  -0.31031321  0.46075168  0.48150009  0.42594237]
 [ 0.51391807  0.29887938 -0.36584369 -0.3772343  -0.01436075  0.09969217
   0.16621869 -0.36411946 -0.26669449  0.30954439]
 [ 0.39827655  0.34765887 -0.41865007  0.448624    0.22669386 -0.0946078
  -0.42547371 -0.32955768  0.19085705 -0.34382109]
 [-0.45843617  0.37862514  0.36735467 -0.06632179  0.26625785 -0.16432429
  -0.01692113 -0.40576807 -0.34648218  0.44601598]
 [-0.11005522 -0.00694831 -0.36493991  0.54002621  0.20089622 -0.36770803
   0.30730359  0.45971254 -0.39054296 -0.26774414]
 [ 0.34525525 -0.30527559 -0.15663247 -0.11799557  0.29826432  0.39942296
  -0.20636361  0.4034583  -0.37450985 -0.28562374]
 [-0.17867363 -0.13081558  0.2817894  -0.06828253  0.06647165  0.07515953
  -0.01374714 -0.05038179 -0.29273299  0.31121308]
 

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [71]:
X = np.random.normal(loc=5, scale=2., size=1000)
x = np.mean(X)
d = (1/X.shape[0])*(sum((X-x)**2))
print(x, d)

5.00981788639 3.83513986153


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [28]:
def foo(a):
    x = np.arange(a)
    for i in range(1,a):
        addition = np.hstack((np.arange(i,a),np.arange(0,i)))
        x = np.vstack((x, addition))
    return x

print (foo(6))   

[[0 1 2 3 4 5]
 [1 2 3 4 5 0]
 [2 3 4 5 0 1]
 [3 4 5 0 1 2]
 [4 5 0 1 2 3]
 [5 0 1 2 3 4]]
